'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Gallery

    Partial Public Class Voting

        '''<summary>
        '''tdTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitle As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''rowTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowTitle As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''tblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblTitle As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''imgTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgTitle As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lnkTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkTitle As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''imgVoteSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgVoteSummary As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lnkThumb control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkThumb As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''tblDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblDetails As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''rowDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowDetails As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''tblViewVote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblViewVote As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''rowResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowResult As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''tdResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdResult As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''lblResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rowName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowName As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''tdName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdName As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''lblName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rowDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowDate As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''tdCreatedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdCreatedDate As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''lblDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rowAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowAuthor As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''tdAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdAuthor As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''lblAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rowDecription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowDecription As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''tdDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdDescription As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''lblDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnAddVote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddVote As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''rowAddVote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowAddVote As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''tblAddVote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblAddVote As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''tdYourRating control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdYourRating As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''lstVote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstVote As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''tdYourComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdYourComments As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''plComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plComments As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtComment As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''btnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''dlVotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dlVotes As Global.System.Web.UI.WebControls.DataList

        '''<summary>
        '''btnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBack As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
